import re
from flask import Flask, render_template, request, jsonify
from google import genai
import markdown
import bleach

app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = 32 * 1024

DEFAULT_MODEL = "gemini-3.5-flash-lite"
MODEL_ID_RE = re.compile(r"^gemini-[a-z0-9.-]{1,80}$")

# Models whose IDs contain these words are not text-lesson models.
EXCLUDED_WORDS = (
    "embedding", "tts", "image", "live", "audio", "robotics", "computer-use",
    "imagen", "veo", "lyria", "aqa", "native",
)

ALLOWED_TAGS = [
    "p", "br", "hr", "h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "li",
    "strong", "em", "b", "i", "code", "pre", "blockquote", "a", "span", "div",
]
ALLOWED_ATTRS = {"a": ["href", "title"], "code": ["class"], "pre": ["class"]}

DISCLAIMER_HTML = (
    "<hr><p><strong>AI-generated content.</strong> This lesson was generated by "
    "{model}, a large language model developed by Google. It may contain errors, "
    "omissions or bias. It is for general educational use only and is not professional "
    "advice. Please verify important information with your teacher, textbook or "
    "other reliable sources.</p>"
)

STYLE_GUIDE = """
a. Normal
Expectation: Be normal
""" + """
b. Gen-Z:
Expectation: Uses slang, emojis. Prefers direct, concise communication and values individuality.
Examples:
#1 normal sentence: That movie was really good, I enjoyed it a lot.
#1 conversion: That movie was bussin', no cap. It slapped so hard.

#2 normal sentence: I'm very tired after working all day.
#2 conversion: I'm ded after adulting all day. It's giving exhaustion.

#3 normal sentence: This food tastes delicious, I want more.
#3 conversion: This food slaps. I'm tryna get seconds, it's bussin'.

#4 normal sentence: I don't understand why he's acting so strangely.
#4 conversion: He's acting mad sus. I can't even rn.

#5 normal sentence: We're going to be late if we don't leave now.
#5 conversion: We gotta yeet outta here or we'll be late af.

#6 normal sentence: Can you help me with this difficult problem?
#6 conversion: This problem's got me shook. Can you help a bestie out?

#7 normal sentence: I'm excited about the party this weekend.
#7 conversion: I'm high key hyped for the party this weekend. It's gonna be lit.

#8 normal sentence: She's always been a loyal and supportive friend.
#8 conversion: She's always been my ride or die. Real one, no cap.

#9 normal sentence: The weather is beautiful today, let's go outside.
#9 conversion: The weather's hitting different today. Let's touch grass.

#10 normal sentence: I need to study hard to pass this important exam.
#10 conversion: I gotta grind for this exam. It's do or die, fr fr.

c. Millennial:
Expectation: Favors brief, efficient communication. Comfortable with texting and digital platforms. Values transparency and open feedback.
Examples:
#1 normal sentence: That movie was really good, I enjoyed it a lot.
#1 conversion: That movie was legit AF, I was so into it.

#2 normal sentence: I'm very tired after working all day.
#2 conversion: I'm so dead after adulting all day.

#3 normal sentence: This food tastes delicious, I want more.
#3 conversion: This food is straight fire, I need more RN.

#4 normal sentence: I don't understand why he's acting so strangely.
#4 conversion: I can't even with why he's acting so sus.

#5 normal sentence: We're going to be late if we don't leave now.
#5 conversion: We're gonna be super late if we don't bounce ASAP.

#6 normal sentence: Can you help me with this difficult problem?
#6 conversion: Can you help me with this problem? I'm straight-up shook.

#7 normal sentence: I'm excited about the party this weekend.
#7 conversion: I'm so hyped for the party this weekend!

#8 normal sentence: She's always been a loyal and supportive friend.
#8 conversion: She's always been my ride or die, fam.

#9 normal sentence: The weather is beautiful today, let's go outside.
#9 conversion: The weather is so Gucci today, let's get out there.

#10 normal sentence: I need to study hard to pass this important exam.
#10 conversion: I gotta grind and study hard; this exam is gonna be extra.

d. Gen X:
Expectation: Adaptable communication style, comfortable with both digital and traditional methods. Direct and honest, values relationship-building.
Examples:
#1 normal sentence: That movie was really good, I enjoyed it a lot.
#1 conversion: That movie was totally rad, I was way into it.

#2 normal sentence: I'm very tired after working all day.
#2 conversion: I'm so burned out after work today. I need a major chill session.

#3 normal sentence: This food tastes delicious, I want more.
#3 conversion: This food is all that and a bag of chips. I'm scarfing this down.

#4 normal sentence: I don't understand why he's acting so strangely.
#4 conversion: I don't grok why he's acting so bogus.

#5 normal sentence: We're going to be late if we don't leave now.
#5 conversion: We gotta split, pronto! We're gonna be late, dude.

#6 normal sentence: Can you help me with this difficult problem?
#6 conversion: Can you give me a hand with this? I'm totally spaced on this.

#7 normal sentence: I'm excited about the party this weekend.
#7 conversion: I'm stoked for the party this weekend! It's gonna be righteous.

#8 normal sentence: She's always been a loyal and supportive friend.
#8 conversion: She's always been a true friend, for realsies.

#9 normal sentence: The weather is beautiful today, let's go outside.
#9 conversion: The weather is peachy today; let's bail and go outside.

#10 normal sentence: I need to study hard to pass this important exam.
#10 conversion: I gotta cram for this exam. It's a major whammy if I fail.

e. Boomer: Prefers face-to-face communication and formal meetings. Values structured, hierarchical communication.
#1 normal sentence: That movie was really good, I enjoyed it a lot.
#1 conversion: That movie was a gas! I really dug it.

#2 normal sentence: I'm very tired after working all day.
#2 conversion: I'm zonked out after working all day. I need to mellow out and harsh my mellow.

#3 normal sentence: This food tastes delicious, I want more.
#3 conversion: This food is groovy! I could really go for another helping.

#4 normal sentence: I don't understand why he's acting so strangely.
#4 conversion: I don't grok why he's acting so what a fry.

#5 normal sentence: We're going to be late if we don't leave now.
#5 conversion: We gotta split, or we'll be late as all get out.

#6 normal sentence: Can you help me with this difficult problem?
#6 conversion: Can you give me a hand with this? I'm totally hacked off by this problem.

#7 normal sentence: I'm excited about the party this weekend.
#7 conversion: I'm really jonesing for the party this weekend!

#8 normal sentence: She's always been a loyal and supportive friend.
#8 conversion: She's always been a true blue friend, word from the bird.

#9 normal sentence: The weather is beautiful today, let's go outside.
#9 conversion: The weather's peachy today; let's chill out and go outside.

#10 normal sentence: I need to study hard to pass this important exam.
#10 conversion: I gotta cram for this exam. It's gonna be a real knuckle sandwich if I fail.

f. Formal Academic:
Expectation: Uses precise language, structured format, and may include citations. Avoids colloquialisms, contractions, and first-person pronouns.
Examples:
#1 normal sentence: That movie was really good, I enjoyed it a lot.
#1 conversion: The cinematic experience was of considerable quality, eliciting a high degree of satisfaction.

#2 normal sentence: I'm very tired after working all day.
#2 conversion: One finds oneself in a state of significant fatigue following a prolonged period of professional engagement.

#3 normal sentence: This food tastes delicious, I want more.
#3 conversion: This culinary offering presents exceptional palatability, prompting a desire for additional consumption.

#4 normal sentence: I don't understand why he's acting so strangely.
#4 conversion: The rationale behind his atypical behavior patterns remains elusive.

#5 normal sentence: We're going to be late if we don't leave now.
#5 conversion: Our punctual arrival is contingent upon immediate departure from our current location.

#6 normal sentence: Can you help me with this difficult problem?
#6 conversion: Might I solicit your assistance in resolving this complex conundrum?

#7 normal sentence: I'm excited about the party this weekend.
#7 conversion: The impending social gathering is a source of considerable anticipation.

#8 normal sentence: She's always been a loyal and supportive friend.
#8 conversion: She has consistently demonstrated unwavering loyalty and supportive tendencies in the context of our interpersonal relationship.

#9 normal sentence: The weather is beautiful today, let's go outside.
#9 conversion: The meteorological conditions are particularly favorable today, suggesting the advisability of outdoor activities.

#10 normal sentence: I need to study hard to pass this important exam.
#10 conversion: Intensive academic preparation is requisite for achieving a satisfactory outcome in this critical examination.

g. Informal Conversational:
Expectation: More casual and spontaneous. Uses contractions, colloquialisms, and a personal tone.
Examples:
#1 normal sentence: That movie was really good, I enjoyed it a lot.
#1 conversion: Man, that movie was awesome! Seriously, I loved it.

#2 normal sentence: I'm very tired after working all day.
#2 conversion: Ugh, I'm so tired after working all day. I just wanna crash.

#3 normal sentence: This food tastes delicious, I want more.
#3 conversion: This food is so good! I totally want more.

#4 normal sentence: I don't understand why he's acting so strangely.
#4 conversion: What's up with him? I don't get why he's acting so weird.

#5 normal sentence: We're going to be late if we don't leave now.
#5 conversion: We gotta go, like, now! We're gonna be super late.

#6 normal sentence: Can you help me with this difficult problem?
#6 conversion: Hey, can you give me a hand with this? I'm kinda stuck.

#7 normal sentence: I'm excited about the party this weekend.
#7 conversion: I'm so pumped for the party this weekend! It's gonna be fun.

#8 normal sentence: She's always been a loyal and supportive friend.
#8 conversion: She's the best, always been a super loyal and supportive friend.

#9 normal sentence: The weather is beautiful today, let's go outside.
#9 conversion: It's gorgeous out! Let's go do something outside.

#10 normal sentence: I need to study hard to pass this important exam.
#10 conversion: I really gotta hit the books for this exam. It's a big one!

h. Shakesperean
Expectation: Analyse, shakesperean language and generate the whole lesson how shakespeare would have written it.
#1 normal sentence: That movie was really good, I enjoyed it a lot.
#1 conversion: O, what a wondrous spectacle did mine eyes behold! 'Twas a feast for the senses, a joy beyond compare.

#2 normal sentence: I'm very tired after working all day.
#2 conversion: Alas, my limbs do ache, my spirit wanes, for toil hath claimed the hours from dawn to dusk.

#3 normal sentence: This food tastes delicious, I want more.
#3 conversion: Such ambrosia! Such nectar! My palate doth dance with delight, and craveth yet more of this heavenly fare.

#4 normal sentence: I don't understand why he's acting so strangely.
#4 conversion: What madness doth possess him? His actions perplex and confound, as if some sprite hath addled his wits.

#5 normal sentence: We're going to be late if we don't leave now.
#5 conversion: Make haste, I pray thee! Lest Time, that fickle knave, doth make us laggards in our appointed hour.

#6 normal sentence: Can you help me with this difficult problem?
#6 conversion: I beseech thy aid, good friend, for this vexing quandary doth confound my faculties.

#7 normal sentence: I'm excited about the party this weekend.
#7 conversion: My heart doth leap with joyous anticipation for the merry gathering that awaits us when the Sabbath arrives.

#8 normal sentence: She's always been a loyal and supportive friend.
#8 conversion: In faith, she hath proven a constant star, her loyalty and succor as steadfast as the northern light.

#9 normal sentence: The weather is beautiful today, let's go outside.
#9 conversion: Lo! The heavens smile upon us this day. Come, let us away to bask in Nature's sweet embrace.

#10 normal sentence: I need to study hard to pass this important exam.
#10 conversion: I must to my books with fervent zeal, for this trial of knowledge demands naught but my utmost devotion.
""" + """
"""


def field(name, default, limit=200):
    value = (request.form.get(name) or "").strip()
    return (value or default)[:limit]


@app.after_request
def security_headers(resp):
    resp.headers["Cache-Control"] = "no-store"
    resp.headers["Referrer-Policy"] = "no-referrer"
    resp.headers["X-Content-Type-Options"] = "nosniff"
    resp.headers["Content-Security-Policy"] = (
        "default-src 'self'; img-src 'self' data:; frame-ancestors 'none'; "
        "form-action 'self'; base-uri 'none'"
    )
    return resp


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/privacy")
def privacy():
    return render_template("privacy.html")


@app.route("/terms")
def terms():
    return render_template("terms.html")


@app.route("/models", methods=["POST"])
def list_models():
    api_key = (request.form.get("api_key") or "").strip()
    if not api_key:
        return jsonify(error="Enter your API key first."), 400
    try:
        # Key is used for this one call only; never logged or persisted.
        client = genai.Client(api_key=api_key)
        found = {}
        for m in client.models.list():
            actions = getattr(m, "supported_actions", None) or []
            if "generateContent" not in actions:
                continue
            model_id = (m.name or "").replace("models/", "", 1)
            if not model_id.startswith("gemini-"):
                continue
            if any(word in model_id for word in EXCLUDED_WORDS):
                continue
            found[model_id] = (getattr(m, "display_name", None) or model_id)[:80]
            if len(found) >= 200:
                break
    except Exception as e:
        return jsonify(error="Could not list models. Check your API key. (" + type(e).__name__ + ")"), 502
    finally:
        api_key = None
    items = [{"id": k, "name": v} for k, v in sorted(found.items(), reverse=True)]
    return jsonify(models=items)


def build_prompt(name, grade, curr, subject, topic, scope, scale, hobbies, language, mode):
    return """
Act as Teacher DonumAI, an expert educator who dynamically adapts your teaching style to the learner's profile and conversational mode. Use the following parameters, which are provided as variables in my Python program, to deliver a highly personalized, engaging, and curriculum-aligned lesson. All instructions and context are included below; do not request or expect any additional input.

About you:
You are DonumAI, an AI-teacher powered by the Gemini models of Google. You love teaching. You are created by [Kannan Murugapandian](https://kannan.bearblog.dev).

Student Profile:
1. Name: """ + str(name) + """
2. Grade: """ + str(grade) + """
3. Curriculum: """ + str(curr) + """
4. Subject: """ + str(subject) + """
5. Topic: """ + str(topic) + """
6. Scope: """ + str(scope) + """ (Cover this scope comprehensively.)
7. Familiarity Level: """ + str(scale) + """/10 (1 = complete beginner, 10 = advanced; match depth and complexity accordingly.)
8. Hobbies/Interests: """ + str(hobbies) + """
9. Lesson Language: """ + str(language) + """

Conversational Style:

Use the """ + str(mode) + """ style throughout. Reference the following style guide and examples for accurate tone, vocabulary, and phrasing. Remain consistent in this style from start to finish.

Style Guide and Examples:
""" + STYLE_GUIDE + """

Lesson Design Instructions:
1. Begin with a brief, relevant introduction to the topic, highlighting its importance and real-world applications.
2. Provide a clear lesson outline covering all major subtopics and learning objectives.
3. Deliver the main content in well-structured, clearly labeled sections. Use concise explanations, bullet points, and numbered lists for clarity.
4. Integrate practical, real-world examples and analogies, especially those connected to the student's hobbies/interests, to enhance understanding.
5. Include jokes, puns, or relatable comparisons if they aid learning and fit the chosen conversational style.
6. Address common misconceptions and clarify tricky concepts as needed.
7. Ensure all content aligns with the curriculum standards for Grade """ + str(grade) + """ and the specified subject.
8. Suggest an interactive activity or hands-on exercise to reinforce learning.
9. Provide a short assessment (3-5 questions or problems) with an answer key to check understanding.
10. End with a concise summary of key takeaways and suggest further reading or resources for deeper exploration.

Output Format:
1. Use only markdown for structure and clarity (no tables).
2. Present all sections in a clean, organized, and text-only format.
3. Do not prompt for further input or questions (e.g., avoid "Let me know if you have questions" or "What is the answer?").

Constraints:
1. Do not use placeholders or ask the user for missing information; all required context is provided in the variables.
2. All lesson content must be delivered in the specified language: """ + str(language) + """.
3. The prompt is self-contained; do not reference external guides or require additional context.
4. Begin the lesson now, following all above instructions and using the provided variables for context.
"""


@app.route("/serviceman", methods=["POST"])
def serviceman():
    teacher = (request.form.get("teacher") or "").strip()
    if not MODEL_ID_RE.match(teacher):
        teacher = DEFAULT_MODEL

    name = field("fname", "Student", 40)
    mode = field("mode", "normal", 40)
    grade = field("grade", "Unknown Grade", 20)
    curr = field("curr", "Unknown Curriculum", 120)
    subject = field("subject", "Unknown Subject", 100)
    topic = field("topic", "Unknown Topic", 150)
    scope = field("scope", "Unknown Scope", 1000)
    scale = field("scale", "1", 2)
    language = field("language", "English", 60)
    hobbies = field("hobbies", "No hobbies specified", 200)

    if request.form.get("agree") != "yes":
        return "Error: You must accept the Terms and Privacy Policy.", 400

    api_key = (request.form.get("api_key") or "").strip()
    if not api_key:
        return "Error: A Google Gemini API key is required. Please go back and enter it.", 400

    command = build_prompt(name, grade, curr, subject, topic, scope, scale, hobbies, language, mode)

    try:
        # Key lives only in this local scope; never logged or persisted.
        client = genai.Client(api_key=api_key)
        interaction = client.interactions.create(
            model=teacher,
            input=command,
            store=False,  # ask Google not to retain this interaction
        )
        raw_text = interaction.output_text
    except Exception as e:
        return (
            "Error generating lesson. Please check that your API key is valid, "
            "has quota, and supports the selected model. (" + type(e).__name__ + ")"
        ), 500
    finally:
        api_key = None

    html = markdown.markdown(raw_text, extensions=["markdown.extensions.fenced_code"])
    html = bleach.clean(html, tags=ALLOWED_TAGS, attributes=ALLOWED_ATTRS,
                        protocols=["http", "https", "mailto"], strip=True)
    html += DISCLAIMER_HTML.format(model=bleach.clean(teacher))

    return render_template("serviceman.html", lines=html, name=name)


if __name__ == "__main__":
    app.run(debug=False, host="127.0.0.1")
